secrets: secrets.yml
templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.pass}}'
      ratio: 0.001
    verify_ssl_certificates: no
#___________________________________________
tasks:
  tvshows:
    priority: 1
    include: tvseries.yml
    list_add:
      - trakt_list:
          username: Addicted5
          account: traktuser
          list: collection
          type: shows
    send_telegram:
      recipients:
        - username: '{{secrets.tg.user}}'
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      template: |
        *{{series_name}}*
        *{{title}}*
        *Size- [{{content_size}}] MB*
        [{{imdb_url}}]
#___________________________________________
  horrible:
    priority: 2
    include: horribleanime.yml
    imdb_lookup: yes
    send_telegram:
      recipients:
        - username: '{{secrets.tg.user}}'
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      template: |
        *{{series_name}}*
        *{{title}}*
        *Size- [{{content_size}}] MB*
        [{{imdb_url}}]
#___________________________________________
  hdanime:
    priority: 3
    include: hdanime.yml
#___________________________________________
  fill_ToDownload:
    priority: 4
    template:
      - no_global
    seen: local
    imdb_list:
      login: '{{secrets.imdb.user}}'
      password: '{{secrets.imdb.pass}}'
      list: watchlist
    accept_all: yes
    imdb_lookup: yes
    list_add:
      - movie_list: ToDownload
    list_queue:
      - imdb_list:
          login: '{{secrets.imdb.user}}'
          password: '{{secrets.imdb.pass}}'
          list: watchlist
#___________________________________________
  disc_1080p_mov:
    priority: 5
    include: movies.yml
    quality:
      - 1080p
    content_size:
      min: 1000
      max: 2800
      strict: no
    send_telegram:
      recipients:
        - username: '{{secrets.tg.user}}'
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      template: |
        *{{imdb_name}} 1080p*
        {{title}}
        *Size-* [{{content_size}}]
        *Rating-* [{{imdb_score}}]/10
        [{{imdb_votes}}] Votes
        *Plot-* [{{imdb_plot_outline}}]
        [{{imdb_url}}]
#___________________________________________
  disc_720p_mov:
    priority: 6
    include: movies.yml
    quality:
      - 720p
    content_size:
      min: 550
      max: 1400
      strict: no
    send_telegram:
      recipients:
        - username: '{{secrets.tg.user}}'
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      template: |
        *{{imdb_name}}  720p*
        {{title}}
        *Size-* [{{content_size}}]
        *Rating-* [{{imdb_score}}]/10
        [{{imdb_votes}}] Votes
        *Plot-* [{{imdb_plot_outline}}]
        [{{imdb_url}}]
#___________________________________________
  disc_movie:
    priority: 7
    include: movies.yml
    quality:
      - 1080p
      - 720p
    content_size:
      min: 550
      max: 4200
      strict: no
    send_telegram:
      recipients:
        - username: '{{secrets.tg.user}}'
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      template: |
        *{{imdb_name}}*
        {{title}}
        *Size-* [{{content_size}}]
        *Quality-*720p-1080p
        *Rating-* [{{imdb_score}}]/10
        [{{imdb_votes}}] Votes
        *Plot-* [{{imdb_plot_outline}}]
        [{{imdb_url}}]
#___________________________________________
  ondisk_imdb:
    priority: 8
    template:
      - no_global
    movie_list: OnDisk
    imdb_lookup: yes
    accept_all: yes
    list_add:
      - imdb_list:
          login: '{{secrets.imdb.user}}'
          password: '{{secrets.imdb.pass}}'
          list: OnDisk
      - trakt_list:
          username: Addicted5
          account: traktuser
          list: collection
          type: movies
    list_queue:
      - movie_list: OnDisk
#___________________________________________
schedules: 
  - tasks: [hdanime]
    interval:
      hours: 16
  - tasks: [tvshows]
    schedule:
      hour: 5-13
      minute: "*/25"
  - tasks: [fill_ToDownload]
    interval:
      days: 2
  - tasks: [disc_1080p_mov, disc_720p_mov, disc_movie]
    interval:
      days: 1
  - tasks: [ondisk_imdb]
    interval:
      days: 4
  - tasks: [horrible]
    schedule:
      day_of_week: thu,fri,sat,sun
      minute: "*/45"
#___________________________________________
web_server:
  bind: 0.0.0.0
  port: 9090
api: yes
webui: yes